export { default as TopBar } from '../component/topBar/TopBar';
export { default as News } from './news/News';
export { default as Portfolio } from '../component/portfolio/Portfolio';
export { default as Intro } from '../component/intro/Intro';
export { default as Footer } from '../component/footer/Footer';
export { default as Contacts } from '../component/contacts/Contacts';
export { default as Menu } from '../component/menu/Menu';
export { default as NewsItem } from '../component/news/NewsItem';
export { default as PortfolioCats } from '../component/portfolio/PortfolioCats';